source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PinAuto_Example' do
  pod "PinAuto", :path => "../"
end

target 'PinAuto_Tests' do
  pod "PinAuto", :path => "../"

  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
